[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
default_args = [ "-lparachain=debug" ]
chain = "westend-local"
command = "polkadot"

	[[relaychain.nodes]]
	name = "alice"
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
	validator = true

	[[relaychain.nodes]]
	name = "dave"
	validator = true

[[parachains]]
id = 1000
chain = "asset-hub-westend-local"
cumulus_based = true
default_args = [ "-lparachain=debug", "--authoring slot-based" ]

	[[parachains.collators]]
	name = "collator-alice"
	validator = true
	command = "polkadot-parachain"

	# run bob as parachain collator
	[[parachains.collators]]
	name = "collator-0"
	command = "polkadot-parachain"

	# run charlie as parachain collator
	[[parachains.collators]]
	name = "collator-1"
	command = "polkadot-parachain"

	# run dave as parachain collator
	[[parachains.collators]]
	name = "collator-2"
	command = "polkadot-parachain"

	# run eve as parachain collator
	[[parachains.collators]]
	name = "collator-3"
	command = "polkadot-parachain"

	# run ferdie as parachain collator
	[[parachains.collators]]
	name = "collator-4"
	command = "polkadot-parachain"
