[package]
name = "pallet-revive-zombienet"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Zombienet integration tests for pallet-revive."

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["full"] }
log = { workspace = true }
pallet-revive = { workspace = true }
pallet-revive-eth-rpc = { workspace = true }
pallet-revive-fixtures = { workspace = true, default-features = true }
serde_json = { workspace = true }
sp-core = { workspace = true, default-features = true }
subxt = { workspace = true, default-features = true, features = ["reconnecting-rpc-client"] }
subxt-signer = { workspace = true, features = ["unstable-eth"] }
tokio = { workspace = true, features = ["full"] }
# Zombienet dependencies
cumulus-zombienet-sdk-helpers = { workspace = true }
zombienet-configuration = { workspace = true }
zombienet-orchestrator = { workspace = true }
zombienet-sdk = { workspace = true }

# Polkadot dependencies
polkadot-primitives = { workspace = true, default-features = true }

[dev-dependencies]
# Additional test dependencies can be added here if needed
